### ISSUE TITLE
Java 9: Project can't be compiled if it has module-info

### ISSUE THREAD

**Issue by remal** [testcontainers/testcontainers-java#1524]
I have a JPMS project with `module-info.java` file. And I have [split package](https://msayag.github.io/SplitPackage/) issue when I'm trying to compile the project.

Java 8 public support ends in 2020. It's pretty soon. IMHO it makes sense to start developing Testcontainers using newer version of Java and targeting Java 8 bytecode.

**Comment by kiview** [comment]
As far as I understand it, we would solve this issue once we solve #1523, correct?

**Comment by remal** [comment]
@kiview , unfortunately no. It requires some refactoring that will break backward compatibility. JPMS requires modules not to share same packages. In other words if a module has classes within package `a.b.c` no other module can have classes within the package. But other module can have classes within subpackages like `a.b.c.d`.

**Comment by remal** [comment]
@rnorth Can we have this issue fixed in 2.0?

BTW I can help by submitting a PR, but there should be some maintainers' decision, as the PR will break backward compatibility.

**Comment by remal** [comment]
The issue is still actual

**Comment by m-rossini** [comment]
Is there any decisions/updates on this issue?

**Comment by unitydynamics** [comment]
Years later, and unfortunately testcontainers still does not support modern Java (that use JMPS  - modules).  What a shame!

The error: **<user package> reads package org.testcontainers.containers from both testcontainers and mongodb** (or whatever module)
