### ISSUE TITLE
Unexpected behavior for database containers launched via JDBC URL scheme

### ISSUE THREAD

**Issue by Lewox** [testcontainers/testcontainers-java#2544]
Version: 1.13.0
Spring Boot: yes
Container: mariadb:10.4

According to [Database containers launched via JDBC URL scheme](https://www.testcontainers.org/modules/databases/#database-containers-launched-via-jdbc-url-scheme)'s note:
We will use /// (host-less URIs) from now on to emphasis the unimportance of the host:port pair.
From Testcontainers' perspective, jdbc:mysql:5.7.22://localhost:3306/databasename and jdbc:mysql:5.7.22:///databasename is the same URI.

This URL `jdbc:tc:mariadb:10.4:///users?TC_INITSCRIPT=sql/init.sql` should behave as `jdbc:tc:mariadb:10.4://localhost:33306/users?TC_INITSCRIPT=sql/init.sql`

The result for the first is URL is:
Waiting for database connection to become available at jdbc:mariadb://localhost:32795/test using query 'SELECT 1'

This results in failed TC_INITSCRIPT due to permissions.

For the second is:
Waiting for database connection to become available at jdbc:mariadb://localhost:32797/users using query 'SELECT 1'

This might be missing from #566 and #617.

**Comment by vektory79** [comment]
Hi! Same here with postgresql in Testcontainers 1.3.0.

In [org.testcontainers.containers.JdbcDatabaseContainer#createConnection](https://github.com/testcontainers/testcontainers-java/blob/f1565f1ba842ccfa9d8ed9ee00276f38b7a2546f/modules/jdbc/src/main/java/org/testcontainers/containers/JdbcDatabaseContainer.java#L189) the `url` is assigned to the value: 
```
jdbc:postgresql://localhost:33048/test?loggerLevel=OFF?password=somepwd&fsync=off&initScript=&volumePath=/media/data/Docker/src/javister/javister-docker-postgresql/tests/simple/target/test-classes/../simpleWithVolumeTest-9_5&user=system
``` 
Note the `?loggerLevel=OFF?` substring, that lead to the error. It's because the `getJdbcUrl` method is [returning string](https://github.com/testcontainers/testcontainers-java/blob/16fda4216018d94f2bf9c20379d3a3573050a06c/modules/postgresql/src/main/java/org/testcontainers/containers/PostgreSQLContainer.java#L65):
```
jdbc:postgresql://localhost:33048/test?loggerLevel=OFF
```
in one hand, and the `ConnectionUrl.getQueryString` method [starts constructing](https://github.com/testcontainers/testcontainers-java/blob/4266fda1f35be31ca0a4a6101a2afae8fba09195/modules/jdbc/src/main/java/org/testcontainers/jdbc/ConnectionUrl.java#L129) the query from the `?` symbol again.

**Comment by vektory79** [comment]
One more thing: I have update the PostgreSQL JDBC driver from version 42.0.0 to 42.2.12.

**Comment by bsideup** [comment]
@vektory79 your issue seems to be unrelated and fixed in #2049

**Comment by Lewox** [comment]
Seems this issue is still valid, it shouldn't be closed.

**Comment by alex-lx** [comment]
Issue still exists with 1.15.1.

**Comment by rnorth** [comment]
@chadlwilson thanks for the prompt. We've removed the stale bot altogether, and I've reopened this issue.

**Comment by eschulma** [comment]
Still a problem in 1.17.6. Could you please update the documentation at least? This cost me a day of effort.

**Comment by molleafauss** [comment]
Can confirm I stumbled upon this also. I have a liquibase script which fails (and very curiously only on _second_ migration, the first gets successfully executed.
The error I get from MySQL is like `ALTER command denied to user 'test'@'172.17.0.1' for table ...`

When adding a hostname:port in the URL, testcontainer correctly creates the database with the expected name and doesn't fail for permissions.

> Testcontainers 1.19.3
> docker:
>  Server Version: 24.0.6
>  API Version: 1.43
>  Operating System: Docker Desktop (macos 13.6.3)

With this url: `jdbc:tc:mysql:8:///rfs`
I see in the logs:
```
Waiting for database connection to become available at jdbc:mysql://localhost:55226/test using query 'SELECT 1'
```
and then the liquibase migration fail with the following (see how the the first migration succeeds):
```
INFO 07/01/2024, 20:45: liquibase: classpath:db/changelog-master.xml: db/changelog-1.0.sql::1::author: Custom SQL executed
INFO 07/01/2024, 20:45: liquibase: classpath:db/changelog-master.xml: db/changelog-1.0.sql::1::author: ChangeSet db/changelog-1.0.sql::1::author ran successfully in 47ms
SEVERE 07/01/2024, 20:45: liquibase: classpath:db/changelog-master.xml: db/changelog-1.0.sql::2::author: Change Set db/changelog-1.0.sql::2::author failed.  Error: ALTER command denied to user 'test'@'172.17.0.1' for table 'Catalog' [Failed SQL: ALTER TABLE rfs.Catalog MODIFY COLUMN id VARCHAR(100)]
```


When I change the url to: `jdbc:tc:mysql:8://localhost/rfs`

```
Waiting for database connection to become available at jdbc:mysql://localhost:55308/rfs using query 'SELECT 1'
[...]

INFO 07/01/2024, 20:47: liquibase: Successfully acquired change log lock
INFO 07/01/2024, 20:47: liquibase: Creating database history table with name: rfs.DATABASECHANGELOG
INFO 07/01/2024, 20:47: liquibase: Reading from rfs.DATABASECHANGELOG
INFO 07/01/2024, 20:47: liquibase: classpath:db/changelog-master.xml: db/changelog-1.0.sql::1::author: Custom SQL executed
INFO 07/01/2024, 20:47: liquibase: classpath:db/changelog-master.xml: db/changelog-1.0.sql::1::author: ChangeSet db/changelog-1.0.sql::1::author ran successfully in 38ms
INFO 07/01/2024, 20:47: liquibase: classpath:db/changelog-master.xml: db/changelog-1.0.sql::2::author: Custom SQL executed
INFO 07/01/2024, 20:47: liquibase: classpath:db/changelog-master.xml: db/changelog-1.0.sql::2::author: ChangeSet db/changelog-1.0.sql::2::author ran successfully in 23ms
[...]
INFO 07/01/2024, 20:47: liquibase: Successfully released change log lock
```
