### ISSUE TITLE
MSSQL Server throws Prelogin Warning but then works.

### ISSUE THREAD

**Issue by marvinosswald** [testcontainers/testcontainers-java#3079]
i get prelogin warning messages after container boot, but it eventually stops and my sql import script runs just fine.
Afterwards the rest of my test runs perfectly, i'd just like to know how i could wait for something or improve this behaviour in anyway.

> Aug 06, 2020 9:17:30 AM com.microsoft.sqlserver.jdbc.SQLServerConnection Prelogin
WARNING: ConnectionID:1 ClientConnectionId: e4e44c35-9473-4c70-ab46-24f526599b5c Prelogin error: host localhost port 32787 Unexpected end of prelogin response after 0 bytes read
Aug 06, 2020 9:17:30 AM com.microsoft.sqlserver.jdbc.SQLServerConnection Prelogin
WARNING: ConnectionID:1 ClientConnectionId: 808607de-dc0c-45b4-bbde-c03e310426d8 Prelogin error: host localhost port 32787 Unexpected end of prelogin response after 0 bytes read
Aug 06, 2020 9:17:31 AM com.microsoft.sqlserver.jdbc.SQLServerConnection Prelogin
WARNING: ConnectionID:1 ClientConnectionId: 6b866882-e0c2-4a93-82d7-5261dc061492 Prelogin error: host localhost port 32787 Unexpected end of prelogin response after 0 bytes read
Aug 06, 2020 9:17:31 AM com.microsoft.sqlserver.jdbc.SQLServerConnection Prelogin
WARNING: ConnectionID:1 ClientConnectionId: d85f4d62-45b0-4b40-b601-a24a2bb3f48e Prelogin error: host localhost port 32787 Unexpected end of prelogin response after 0 bytes read
Aug 06, 2020 9:17:32 AM com.microsoft.sqlserver.jdbc.SQLServerConnection Prelogin
WARNING: ConnectionID:1 ClientConnectionId: 01370df2-2393-4888-8e98-6b2cd8a335e0 Prelogin error: host localhost port 32787 Unexpected end of prelogin response after 0 bytes read
Aug 06, 2020 9:17:33 AM com.microsoft.sqlserver.jdbc.SQLServerConnection Prelogin
WARNING: ConnectionID:1 ClientConnectionId: c57ee0b6-b86c-4a77-a82c-d72e82072595 Prelogin error: host localhost port 32787 Unexpected end of prelogin response after 0 bytes read
Aug 06, 2020 9:17:34 AM com.microsoft.sqlserver.jdbc.SQLServerConnection Prelogin
WARNING: ConnectionID:1 ClientConnectionId: 374d4277-fcd2-4684-a080-ba2c20b91ee7 Prelogin error: host localhost port 32787 Unexpected end of prelogin response after 0 bytes read

This is my **extended MssqlContainer**, i've tried adding a line to wait for a specific log line but it doesn't seem to make any difference.

```java
public class MyMSSQLContainer extends MSSQLServerContainer<MyMSSQLContainer> {
	private static final String IMAGE_VERSION = "mcr.microsoft.com/mssql/server:2017-CU12";
	private static MyMSSQLContainer container;

	private MyMSSQLContainer() {
		super(IMAGE_VERSION);
	}

	public static MyMSSQLContainer getInstance() {
		if (container == null) {
			container = new MyMSSQLContainer().waitingFor(Wait.forLogMessage("*SQL Server is now ready for client connections*", 1));
		}
		return container;
	}

	@Override
	public void start() {
		super.start();
	}

	@Override
	public void stop() {
		//do nothing, JVM handles shut down
	}
}
```

This is my **base test class** where i init the container and run the schema and data init script..
```java
public abstract class AbstractApiTest {
	//for ci testing: https://www.testcontainers.org/supported_docker_environment/continuous_integration/bitbucket_pipelines/
	public static MSSQLServerContainer<MyMSSQLContainer> mssqlServerContainer = MyMSSQLContainer.getInstance();

	@Autowired
	MockMvc mockMvc;

	@Autowired
	ObjectMapper objectMapper;

	static {
		mssqlServerContainer.start();
		ScriptUtils.runInitScript(new JdbcDatabaseDelegate(mssqlServerContainer, ""), "setup.sql");
	}

	static class Initializer implements ApplicationContextInitializer<ConfigurableApplicationContext> {

		public void initialize(ConfigurableApplicationContext configurableApplicationContext) {
			TestPropertyValues
				.of(
					"spring.datasource.url=" + mssqlServerContainer.getJdbcUrl(),
					"spring.datasource.username=" + mssqlServerContainer.getUsername(),
					"spring.datasource.password=" + mssqlServerContainer.getPassword()
				)
				.applyTo(configurableApplicationContext.getEnvironment());
		}
	}
}

**Comment by franklsm1** [comment]
Seeing this same issue as well, when using a r2dbc connection.

**Comment by AB-xdev** [comment]
This problem seems to come from  the mssql-jdbc-driver directly:
https://github.com/microsoft/mssql-jdbc/blob/0f3e0a10f2f85b5b357811907fdb487d63e49830/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L3107-L3118

**Comment by rnorth** [comment]
Hmm, I've not had a chance to dig into this, but it sounds like there's a log warning being emitted when Testcontainers is testing the JDBC connection while the container is starting.

Is the problem just log spam, or is there some other problem?

**Comment by AB-xdev** [comment]
I think it's just log spam (however I'm not 100% sure) looks like the port is exposed but the SQL Server is not fully setup / starting.
After the container/server says ``Server is listening on [ ... ]`` the warning is gone in our tests.

**Comment by tsmets** [comment]
I have a similar issue here :

**Comment by csolem** [comment]
Same here with version `1.16.2`. A hacky workaround that avoids the warnings in our case:

```java
new MSSQLServerContainer<>("mcr.microsoft.com/mssql/server:2017-latest")
      .withStartupCheckStrategy(new MinimumDurationRunningStartupCheckStrategy(Duration.ofSeconds(5)));
```

**Comment by namgaxilem** [comment]
Still getting this issue, the insert and select still successful but still get warning and throw SQLException in Spring RestController:

```
@GetMapping("/v1/user-request/")
public String getUserRequest(@RequestParam Long id) throws SQLException {
    Optional<UserRequest> list = userRequestRepository.findById(id);
    return list.get().getData();
}
```

**Comment by Danielliudov** [comment]
I am experiencing the same issue is there any resolution to it?

**Comment by anderso** [comment]
Same here, annoying stderr messages logged while container is starting up. I believe this loop executing the test query is triggering it:

https://github.com/testcontainers/testcontainers-java/blob/b50cfee16ae15fea876a71b35f1c82d4d0cc51e5/modules/jdbc/src/main/java/org/testcontainers/containers/JdbcDatabaseContainer.java#L142-L182

**Comment by zahidzia** [comment]
Any updates on how to fix this annoying log spam?

**Comment by anderso** [comment]
The mssql jdbc drivers is logging with java util logging to the logger named `com.microsoft.sqlserver.jdbc.Connection`

https://github.com/microsoft/mssql-jdbc/blob/0f3e0a10f2f85b5b357811907fdb487d63e49830/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L1213-L1214

So the easiest way to disable it would be disable the warning level of this logger, how to do it depends on your logging setup.

Another alternative would be to override waitUntilContainerStarted, the question is what to replace it with, is there an alternative way to check if mssql has started? This code is common for all jdbc containers so I'm guessing only the mssql driver logs this as warning or this would have been fixed by now.

Another alternative is to wait for a while so that when this method is called the database should already be up, as suggested above.

**Comment by email2muthu4** [comment]
I am also facing similar issue . Anyone find the solution ?

Jul 28, 2024 1:45:20 PM com.microsoft.sqlserver.jdbc.SQLServerConnection prelogin
WARNING: ConnectionID:1 ClientConnectionId: f4682bb4-bbca-4b39-8bc9-0a031923f52a Prelogin error: host localhost port 61904 Unexpected end of prelogin response after 0 bytes read

**Comment by aistisdev** [comment]
Same issue, but it does not start ever

**Comment by ventod** [comment]
> As mentioned above, the MS SQL JDBC driver uses the `java.util.Logging` which, by default, logs to `stderr`.
> 
> To get rid of the noise, you can override the log level:
> 
> val logger = Logger.getLogger("com.microsoft.sqlserver.jdbc.internals.SQLServerConnection")
> logger.level = Level.SEVERE
> 
> Java:
> 
> Logger logger = Logger.getLogger("com.microsoft.sqlserver.jdbc.internals.SQLServerConnection");
> logger.setLevel(Level.SEVERE);

for me this is not working. I'm still getting tons of

"""
May 16, 2025 4:31:18 PM com.microsoft.sqlserver.jdbc.SQLServerConnection prelogin
WARNING: ConnectionID:2 ClientConnectionId: 680984d2-d2fb-4866-b68b-af61353fbe31 Prelogin error: host localhost port 32824 Unexpected end of prelogin response after 0 bytes read
May 16, 2025 4:31:18 PM com.microsoft.sqlserver.jdbc.SQLServerConnection prelogin
WARNING: ConnectionID:3 ClientConnectionId: 79e5ba0e-6bb2-4fce-9727-d36148eb8ec6 Prelogin error: host localhost port 32824 Error reading prelogin response: Connection reset ClientConnectionId:79e5ba0e-6bb2-4fce-9727-d36148eb8ec6
"""
Which imo should be expected because those logs are coming from inside the container itself

**Comment by nrllewellyn** [comment]
For anyone else having this issue: The cause of this appears to be that `JdbcDatabaseContainer` ignores any configured wait strategies. For the actual fix, I would recommend changing `JdbcDatabaseContainer.waitUntilContainerStarted()` to call `super.waitUntilContainerStarted()` at the top of the method so that any wait conditions are executed before using a JDBC query to check the DB's status.

A work-around for this is to create your own subclass of `MSSQLServerContainer` like this:
```java
public class FixedMssqlContainer extends MSSQLServerContainer<FixedMssqlContainer > {

    public FixedMssqlContainer (DockerImageName dockerImageName) {
        super(dockerImageName);
    }

    @Override
    protected void waitUntilContainerStarted() {
        // Copied from GenericContainer.waitUntilContainerStarted()
        WaitStrategy waitStrategy = getWaitStrategy();
        if (waitStrategy != null) {
            waitStrategy.waitUntilReady(this);
        }

        super.waitUntilContainerStarted();
    }
}
```

And then in your test code:
```java
new FixedMssqlContainer (MSSQL_SERVER_DOCKER_IMAGE)
        .acceptLicense()
        .waitingFor(forLogMessage(".*Service Broker manager has started.*", 1));
```

**Comment by kiview** [comment]
@nrllewellyn You are right that `JdbcDatabaseContainer` subclasses, for legacy reasons, don't allow setting wait strategies (in most cases).

Besides, things really work as expected given a SQL connection based waiting approach, which I don't think we can fix without a different wait strategy approach.
Do MSSQL users consider a log message based approach to be more robust/fast/less noisy? We generally like those and use them in data base implementations as well.

**Comment by nrllewellyn** [comment]
@kiview That's a good point--I wouldn't consider log-based waiting to be as robust. The work-around I used above still uses the connection-based method--it just waits until _after_ the log message.

A couple of thoughts:
- If the current behavior is intentional, I would recommend having `JdbcDatabaseContainer` override the waiting related methods in `GenericTestContainer` (e.g., `waitingFor` and `setWaitStrategy`) to be deprecated and possibly throw an exception. That way you get IDE warnings (deprecation) and runtime failure (exception) instead of unexpected behaviors. (This is similar to what Google's Guava does to tell users that `ImmutableList.add(...)` won't work, for those who are familiar with that library.)
- It might be worth having `JdbcDatabaseContainer` turn off JDBC's logging during the "wait for connection" loop. I would save the current log level and then do a try/finally that sets the log level back to whatever it was at the beginning.

Doing these two things would fix the underlying issue (log spam) while keeping the more robust approach of waiting for the connection to work.

**Comment by kiview** [comment]
Thanks, these are both good suggestions @nrllewellyn. 

> It might be worth having JdbcDatabaseContainer turn off JDBC's logging during the "wait for connection" loop.

Can we do this programmatically? I honestly don't know 🙂

**Comment by ventod** [comment]
Do not know if this as been answered somewhere else but... I solved this issue by

- using the "new" dependency artifact ( [this one](https://mvnrepository.com/artifact/org.testcontainers/testcontainers-mssqlserver) and not [this other one](https://mvnrepository.com/artifact/org.testcontainers/mssqlserver), the difference is in the artifact id, `testcontainers-mssqlserver` vs `mssqlserver` )
- importing `org.testcontainers.mssqlserver.MSSQLServerContainer` and not `org.testcontainers.containers.MSSQLServerContainer` (which is flagged as deprecated now)
