### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-java#85]
Windows isn't currently supported. I'd like to support this, but it will require a bit of an investment in dev tooling and CI, so it may not be especially soon.

Help would be gratefully received in this area, as long as we can get these dev and testing aspects right.

#84 and #62 are current known issues with Windows support.

**Comment by v-schulz** [comment]
I actually started  a branch for Windows support (not uploaded, yet). I think the mentioned tickets are already covered by this implementation however there are some more things to deal with. I hope I get a clean version uploaded the next days. It may be possible that not all functionality can actually be implemented for Windows (especially the ini-file support for mysql is making some trouble because the mounted ini-file has 777 access-rights in the container but it is only allowed to have 644 by mysql, otherwise it is ignored). Additionally, some exceptions (that do not fail the tests though) need to be dealt with.

**Comment by rnorth** [comment]
Ah, thank you! I'll look forward to hearing how it goes.

Do you have any thoughts on running automated tests for this in the future? There don't seem to be any cloud CI services with both Windows and Docker support, unless I'm missing anything...

**Comment by swissarmykirpan** [comment]
https://github.com/StefanScherer/windows-docker-builder

**Comment by rnorth** [comment]
Interesting! I'd seen AppVeyor but thought it ran builds inside a VM (and hence docker-machine wouldn't be able to spawn another VM within it). Seems as though I might have been mistaken though. Cheers!

**Comment by v-schulz** [comment]
The current version which fixes most of the errors is online at [my fork](https://github.com/v-schulz/testcontainers-java/commits/windows-support).

There are two issues unresolved which I can't figure out how to best deal with them:
- all tests pass except for the mysql test using a mounted ini file; I couldn't find a way how to deal with the problem mentioned above (access rights inside the container for mounted files are 777 but need to be 644 for mysql ini files).
- CI doesn't seem to be possible with AppVeyor for our case. I tried different setups but the container won't start another VM inside (at least with the configurations I tried including the one mentioned by swissarmykirpan).

The tests stillt throw some exxceptions but that is not a windows specific issue or an issue for this case.

Nevertheless, you are welcome to comment on the current implementation. Because of the small changes that were necessary I decided against additional classes for OS specific code.

**Comment by rnorth** [comment]
That's really cool, thank you. I'll try and have a play with this on a
Windows VM!
Rich

**Comment by rnorth** [comment]
Hi @v-schulz 
Sorry for not finding much time to look at this yet. I still need to set up a suitable windows VM to play with this properly, but time has been hard to find recently.

Looking at your code, would I be right in thinking that there's a hard requirement on MinGW? Could this be made to work without MinGW?

My preference would be that for a Windows user there are no installation requirements beyond Docker Toolbox, Java and Maven/Gradle. If we can get to that it would be awesome.
Thank you
Richard

**Comment by v-schulz** [comment]
Hi @rnorth,

as far as I know currently there is some kind of hard requirement for MinGW because Docker Toolbox installs Git for Windows which uses MinGW (or some variant). So everyone installing Docker Toolbox should also have MinGW.

Last week however, there was some interesting announcement: https://blog.docker.com/2016/03/docker-for-mac-windows-beta/
So if the new Docker for Windows is used then this dependency is not required any more.
In addition this may be helpful in order to get the CI running if there is a possibility to run Hyper-V containers next to each other or inside of another one.

Regards
Viktor

**Comment by rnorth** [comment]
Hi @v-schulz 

Thanks for clarifying - that's good to know.

I think the native support news is very exciting; it certainly could make this easier. I can foresee it becoming something TC needs to support at any rate, so I'm hoping to get in to the beta for it!

I definitely would like to see how it affects the Windows CI situation - fingers crossed. 

In the meantime I'm still open to any creative suggestions about Windows+Docker CI setups. I'm hoping against hope that this isn't going to end with me buying a physical Windows box just for CI ;)

Thanks
Rich

**Comment by rnorth** [comment]
@v-schulz @swissarmykirpan @bsideup @x97mdr @mathiasconradt @MaXal
As you've all commented about Windows support for Testcontainers, I was hoping you wouldn't mind giving your thoughts in this thread...

@v-schulz did the work of setting up Windows support, but the main sticking point has been lack of a good option for CI - we've not yet found any cloud CI solution that allows use of docker, and I'm reluctant to say the library supports Windows if we can't ensure each build is tested. So on this, does anybody have any new information or bright ideas? If the only option is for me to buy a physical windows box I will, but I'd rather not..!

Also, depending on progress, 'native' Docker for Windows might be available by the time we resolve the above. If that were the case, would people prefer that Windows docker-machine support get finalized, or would you prefer that we just skip and work out how to support the native solution first?

Please let me know your thoughts!
Rich

**Comment by swissarmykirpan** [comment]
At Build 2016 Microsoft announced and released a preview version of Windows 10 that has support for running Ubuntu binaries natively.  https://blogs.windows.com/windowsexperience/2016/04/06/announcing-windows-10-insider-preview-build-14316/

This means Windows now supports bash and a whole lot more. E.g you can use apt get and install things like redis. 

Docker for Windows Is now also here! https://blogs.technet.microsoft.com/windowsserver/2016/04/04/build-2016-container-announcements-hyper-v-containers-and-windows-10-and-powershell-for-docker/

It's just a matter of time until appveyor supports the new insider preview build.

**Comment by swissarmykirpan** [comment]
To answer your question:

Maybe you can release Windows as an alpha or a beta? Make it explicit what the issue is with CI until it can be resolved in a better way.

**Comment by bsideup** [comment]
@rnorth any news here? We really want to get Windows support ASAP :)

**Comment by rnorth** [comment]
@bsideup I think I'm OK with @swissarmykirpan's suggestion of releasing as 'alpha' until we can achieve regular automated tests. I think I'm going to have to buy a Windows machine at the weekend so that I can at least do some manual builds... ☹️

**Comment by v-schulz** [comment]
I merged all changes from the current master branch and rebased relevant changes on top. On my Windows system all Maven tests run without problems (except for those that I intentionally changed so they are not executed).

**Comment by rnorth** [comment]
@v-schulz thank you so much - this sounds promising. Please could you create a PR?

I'm thinking that for getting this live we need to do some things - feedback appreciated:

- I still need to get hold of a suitable Windows machine to run my own tests on - sorry but I've still not got this. Until then, though, I'm happy for this to be an alpha release if contributors vouch for it.
- It would probably make sense if we use jitpack for our alpha release (so I've created a named branch `windows-support` for this to reside in)
- We should probably have a documentation page detailing:
    - system requirements (I think Docker Toolbox is enough, but if not, this would be the place to state it)
    - how to obtain the windows branch through jitpack
    - any features that don't work or are untested when running in a windows environment

Does that make sense to everyone?
Cheers,
Rich

**Comment by rnorth** [comment]
Thanks to @v-schulz, Windows support is ready for wider testing. See docs here: http://testcontainers.viewdocs.io/testcontainers-java/usage/windows_support/

**Comment by bsideup** [comment]
Tried Windows support in our project.

Works fine, but the old code didn't work because it wasn't calling "hostAgnosting" FS bind. Since previously Windows support wasn't there, I propose to remove "hostAgnosting" method and use old one, with "if" for Windows. Otherwise, users will have to change it everywhere to get Windows support

**Comment by rnorth** [comment]
@bsideup good point - I'd agree that we want to avoid forcing an API change unless we have to. What do you think @v-schulz?

**Comment by v-schulz** [comment]
Yes, I think that is a good idea. A distinction is unnecessary in this case. I should probably also enhance the MinGW-Path transformer method because currently it is limited to absolute paths.

**Comment by rnorth** [comment]
@v-schulz I've removed this method during merging of master (1.0.5 RC) into the windows support branch

**Comment by valdisrigdon** [comment]
We have run some initial tests and basic Windows support works for us. We are using a `ContainerRule`, exposing ports, and binding a directory.

**Comment by rnorth** [comment]
This is now merged in to the master branch and part of the 1.1.0 release - as always, I'd be grateful for feedback or any issues. I'll close this ticket now, but please open new problems as new issue tickets.
